# Generated by Django 4.0.3 on 2022-04-10 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
