# Generated by Django 4.0.3 on 2022-04-16 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='prod_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='prod_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
