# Generated by Django 4.0.3 on 2022-04-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
